language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - vendor/bin/phing
  - vendor/bin/phpcs -sp --report-junit=build/logs/phpcs.xml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./build/cc-test-reporter
  - chmod +x ./build/cc-test-reporter
  - ./build/cc-test-reporter before-build

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./build/cc-test-reporter after-build
