services:
  php:
    build:
      context: .
      dockerfile: php-8.2.Dockerfile
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    working_dir: /app
  php8.3:
    build:
      context: .
      dockerfile: php-8.3.Dockerfile
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    working_dir: /app
  php8.4:
    build:
      context: .
      dockerfile: php-8.4.Dockerfile
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    working_dir: /app